/*! \file BuiltInTypes.cpp
	\author Alan Ramirez
	\date 2025-11-21
	\brief Registration of the built-in engine types into the reflection database
*/

#include "HushEngine.hpp"

#include "Logger.hpp"
#include "ModuleRegistry.hpp"

// Generated by hush-reflection for every engine target with reflection.
#include <HushCore/RegisterModule.hpp>
#include <HushResources/RegisterModule.hpp>

void Hush::HushEngine::RegisterBuiltInTypes()
{
	Modules::ModuleRegistry *registry = GetModuleRegistry();
	Reflection::ReflectionDB &db = registry->GetReflectionDB();

	// Every engine module function registers the reflected types of its
	// target, owned by the engine module.
	bool success = RegisterModule_HushCore(db, ENGINE_MODULE_HANDLE);
	if (!success)
	{
		LogFormat(ELogLevel::Error, "Failed to register the built-in types of HushCore");
	}
	success = registry->RegisterNativeSystems(ENGINE_MODULE_HANDLE, GetSystemDescriptors_HushCore()) ==
				  Modules::ModuleRegistry::EError::None &&
			  success;

	const bool resourcesRegistered = RegisterModule_HushResources(db, ENGINE_MODULE_HANDLE);
	if (!resourcesRegistered)
	{
		LogFormat(ELogLevel::Error, "Failed to register the built-in types of HushResources");
	}
	success = resourcesRegistered && success;
	success = registry->RegisterNativeSystems(ENGINE_MODULE_HANDLE, GetSystemDescriptors_HushResources()) ==
				  Modules::ModuleRegistry::EError::None &&
			  success;

	if (!success || registry->CommitModuleRegistration(ENGINE_MODULE_HANDLE) != Modules::ModuleRegistry::EError::None)
	{
		LogFormat(ELogLevel::Error, "Failed to complete built-in type registration");
	}
}
