[package]
name = "devtool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
inquire = "0.7.5"
lazy_static = "1.5.0"
regex = "1.11.0"
rfd = "0.15.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
walkdir = "2.5.0"
