# Program options, used to enable/disable certain features, such as vectorization, LTO, etc.

option(HUSH_ENABLE_LTO "Enable Link-Time Optimization" OFF)
option(HUSH_ENABLE_TESTS "Enable tests" ON)
option(HUSH_ENABLE_DOCS "Enable documentation" ON)

if (HUSH_ENABLE_LTO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output)
    if (result)
        message(STATUS "IPO/LTO is supported: ${output}")
    else()
        message(WARNING "IPO/LTO is not supported: ${output}")
    endif()
endif()

if (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(HUSH_CPU_FLAGS /arch:AVX2)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(HUSH_CPU_FLAGS -march=broadwell)
    endif()
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "ARM" OR CMAKE_SYSTEM_PROCESSOR MATCHES "AARCH64")
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
        add_compile_options(/arch:8.1)
        set(HUSH_CPU_FLAGS /arch:8.1)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(HUSH_CPU_FLAGS -march=armv8.1-a+simd)
    endif()
endif()